#!/bin/bash

# Rosetta Stone Package Manager
# https://github.com/Digit/witch/issues/18

#this is just an initial laying out ... much change is expected, and it is not expected to work yet.

PACKAGEMGR=$(sed -n '4p' $WITCH/config.base.txt)

#basics first. AFTER we get these, we can futz over the finer grained nuanced commands.
#install
#remove
#update
#upgrade
#search

if [ $PACKAGEMGR = PORTAGE ]
  if $1 = install
    then emerge $2
  if $1 = remove
    then emerge -C $2
  if $1 = update
    then emerge --sync
  if $1 = upgrade
    then emerge -DuN
  if $1 = search
    if eix #FIXME
      then eix $2
    else
      emerge --search $2

if $PACKAGEMGR = PALUDIS
  if $1 = install
    then = cave resolve $2
  if $1 = remove
    then cave # ~ er, i've forgotten the paludis commands.  ...
# etc

if [ $PACKAGEMGR = APTGET ]
  if $1 = install
    then apt-get install $2
  if $1 = remove
    then apt-get remove $2
  if $1 = update
    then apt-get update
  if $1 = upgrade
    then apt-get upgrade
  if $1 = search
    then apt-cache search $2

if [ $PACKAGEMGR = SLAPTGET ]
  if $1 = install
    then slapt-get install $2
  if $1 = remove
    then slapt-get remove $2
  if $1 = update
    then slapt-get update
  if $1 = upgrade
    then slapt-get upgrade
  if $1 = search
    then slapt-cache search $2  #that right?? FIXME

if [ $PACKAGEMGR = PACMAN ]
  if $1 = install
    then pacman -S $2
  if $1 = remove
    then pacman -Rc $2
  if $1 = update
    then pacman -Sy
  if $1 = upgrade
    then pacman -Syu
  if $1 = search
    then pacman -Ss $2

# ^ something like that.   basic jist.   now clean up, and repeat for other package managers.

# feel free to come up with a better way... this is just an initial jotting down of the concept... not clean code.  SO LETS NOT PUT rspm COMMANDS ANYWHERE UNTIL IT IS REAL WORKING CODE.  ;)
